// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "inventory/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: cxt, uuid
func (_m *PartRepository) GetPart(cxt context.Context, uuid string) (*model.Part, bool) {
	ret := _m.Called(cxt, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, bool)); ok {
		return rf(cxt, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(cxt, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(cxt, uuid)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// PartRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type PartRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - cxt context.Context
//   - uuid string
func (_e *PartRepository_Expecter) GetPart(cxt interface{}, uuid interface{}) *PartRepository_GetPart_Call {
	return &PartRepository_GetPart_Call{Call: _e.mock.On("GetPart", cxt, uuid)}
}

func (_c *PartRepository_GetPart_Call) Run(run func(cxt context.Context, uuid string)) *PartRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PartRepository_GetPart_Call) Return(_a0 *model.Part, _a1 bool) *PartRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartRepository_GetPart_Call) RunAndReturn(run func(context.Context, string) (*model.Part, bool)) *PartRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, req
func (_m *PartRepository) ListParts(ctx context.Context, req *model.PartsFilter) []*model.Part {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) []*model.Part); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	return r0
}

// PartRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type PartRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.PartsFilter
func (_e *PartRepository_Expecter) ListParts(ctx interface{}, req interface{}) *PartRepository_ListParts_Call {
	return &PartRepository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, req)}
}

func (_c *PartRepository_ListParts_Call) Run(run func(ctx context.Context, req *model.PartsFilter)) *PartRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.PartsFilter))
	})
	return _c
}

func (_c *PartRepository_ListParts_Call) Return(_a0 []*model.Part) *PartRepository_ListParts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartRepository_ListParts_Call) RunAndReturn(run func(context.Context, *model.PartsFilter) []*model.Part) *PartRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
