// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OrderPaidConsumerService is an autogenerated mock type for the OrderPaidConsumerService type
type OrderPaidConsumerService struct {
	mock.Mock
}

type OrderPaidConsumerService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderPaidConsumerService) EXPECT() *OrderPaidConsumerService_Expecter {
	return &OrderPaidConsumerService_Expecter{mock: &_m.Mock}
}

// RunOrderPaidConsumer provides a mock function with given fields: ctx
func (_m *OrderPaidConsumerService) RunOrderPaidConsumer(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunOrderPaidConsumer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderPaidConsumerService_RunOrderPaidConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOrderPaidConsumer'
type OrderPaidConsumerService_RunOrderPaidConsumer_Call struct {
	*mock.Call
}

// RunOrderPaidConsumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderPaidConsumerService_Expecter) RunOrderPaidConsumer(ctx interface{}) *OrderPaidConsumerService_RunOrderPaidConsumer_Call {
	return &OrderPaidConsumerService_RunOrderPaidConsumer_Call{Call: _e.mock.On("RunOrderPaidConsumer", ctx)}
}

func (_c *OrderPaidConsumerService_RunOrderPaidConsumer_Call) Run(run func(ctx context.Context)) *OrderPaidConsumerService_RunOrderPaidConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderPaidConsumerService_RunOrderPaidConsumer_Call) Return(_a0 error) *OrderPaidConsumerService_RunOrderPaidConsumer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderPaidConsumerService_RunOrderPaidConsumer_Call) RunAndReturn(run func(context.Context) error) *OrderPaidConsumerService_RunOrderPaidConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderPaidConsumerService creates a new instance of OrderPaidConsumerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPaidConsumerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPaidConsumerService {
	mock := &OrderPaidConsumerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
