// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShipAssembledConsumerService is an autogenerated mock type for the ShipAssembledConsumerService type
type ShipAssembledConsumerService struct {
	mock.Mock
}

type ShipAssembledConsumerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipAssembledConsumerService) EXPECT() *ShipAssembledConsumerService_Expecter {
	return &ShipAssembledConsumerService_Expecter{mock: &_m.Mock}
}

// RunShipAssembledConsumer provides a mock function with given fields: ctx
func (_m *ShipAssembledConsumerService) RunShipAssembledConsumer(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunShipAssembledConsumer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShipAssembledConsumerService_RunShipAssembledConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunShipAssembledConsumer'
type ShipAssembledConsumerService_RunShipAssembledConsumer_Call struct {
	*mock.Call
}

// RunShipAssembledConsumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ShipAssembledConsumerService_Expecter) RunShipAssembledConsumer(ctx interface{}) *ShipAssembledConsumerService_RunShipAssembledConsumer_Call {
	return &ShipAssembledConsumerService_RunShipAssembledConsumer_Call{Call: _e.mock.On("RunShipAssembledConsumer", ctx)}
}

func (_c *ShipAssembledConsumerService_RunShipAssembledConsumer_Call) Run(run func(ctx context.Context)) *ShipAssembledConsumerService_RunShipAssembledConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ShipAssembledConsumerService_RunShipAssembledConsumer_Call) Return(_a0 error) *ShipAssembledConsumerService_RunShipAssembledConsumer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShipAssembledConsumerService_RunShipAssembledConsumer_Call) RunAndReturn(run func(context.Context) error) *ShipAssembledConsumerService_RunShipAssembledConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// NewShipAssembledConsumerService creates a new instance of ShipAssembledConsumerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipAssembledConsumerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipAssembledConsumerService {
	mock := &ShipAssembledConsumerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
