// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ZanDattSu/star-factory/notification/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

type NotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationService) EXPECT() *NotificationService_Expecter {
	return &NotificationService_Expecter{mock: &_m.Mock}
}

// SendAssembledNotification provides a mock function with given fields: ctx, shipAssembledEvent
func (_m *NotificationService) SendAssembledNotification(ctx context.Context, shipAssembledEvent model.ShipAssembledEvent) error {
	ret := _m.Called(ctx, shipAssembledEvent)

	if len(ret) == 0 {
		panic("no return value specified for SendAssembledNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = rf(ctx, shipAssembledEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_SendAssembledNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAssembledNotification'
type NotificationService_SendAssembledNotification_Call struct {
	*mock.Call
}

// SendAssembledNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - shipAssembledEvent model.ShipAssembledEvent
func (_e *NotificationService_Expecter) SendAssembledNotification(ctx interface{}, shipAssembledEvent interface{}) *NotificationService_SendAssembledNotification_Call {
	return &NotificationService_SendAssembledNotification_Call{Call: _e.mock.On("SendAssembledNotification", ctx, shipAssembledEvent)}
}

func (_c *NotificationService_SendAssembledNotification_Call) Run(run func(ctx context.Context, shipAssembledEvent model.ShipAssembledEvent)) *NotificationService_SendAssembledNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShipAssembledEvent))
	})
	return _c
}

func (_c *NotificationService_SendAssembledNotification_Call) Return(_a0 error) *NotificationService_SendAssembledNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationService_SendAssembledNotification_Call) RunAndReturn(run func(context.Context, model.ShipAssembledEvent) error) *NotificationService_SendAssembledNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendPaidNotification provides a mock function with given fields: ctx, paidEvent
func (_m *NotificationService) SendPaidNotification(ctx context.Context, paidEvent model.OrderPaidEvent) error {
	ret := _m.Called(ctx, paidEvent)

	if len(ret) == 0 {
		panic("no return value specified for SendPaidNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = rf(ctx, paidEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_SendPaidNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPaidNotification'
type NotificationService_SendPaidNotification_Call struct {
	*mock.Call
}

// SendPaidNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - paidEvent model.OrderPaidEvent
func (_e *NotificationService_Expecter) SendPaidNotification(ctx interface{}, paidEvent interface{}) *NotificationService_SendPaidNotification_Call {
	return &NotificationService_SendPaidNotification_Call{Call: _e.mock.On("SendPaidNotification", ctx, paidEvent)}
}

func (_c *NotificationService_SendPaidNotification_Call) Run(run func(ctx context.Context, paidEvent model.OrderPaidEvent)) *NotificationService_SendPaidNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaidEvent))
	})
	return _c
}

func (_c *NotificationService_SendPaidNotification_Call) Return(_a0 error) *NotificationService_SendPaidNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationService_SendPaidNotification_Call) RunAndReturn(run func(context.Context, model.OrderPaidEvent) error) *NotificationService_SendPaidNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
