with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True
recursive: true
disable-version-string: true

packages:
  # Inventory service
  github.com/ZanDattSu/star-factory/inventory/internal/service:
    config:
      all: true

  # Inventory repository
  github.com/ZanDattSu/star-factory/inventory/internal/repository:
    config:
      all: true

  # Inventory and Payment clients
  github.com/ZanDattSu/star-factory/order/internal/client/grpc:
    config:
      all: true

  # Order service
  github.com/ZanDattSu/star-factory/order/internal/service:
    config:
      all: true

  # Order repository
  github.com/ZanDattSu/star-factory/order/internal/repository:
    config:
      all: true

  # Payment service
  github.com/ZanDattSu/star-factory/payment/internal/service:
    config:
      all: true