with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  # Inventory service
  inventory/internal/service:
    config:
      all: true

  # Inventory repository
  inventory/internal/repository:
    config:
      all: true

  # Inventory and Payment clients
  order/internal/client/grpc:
    config:
      all: true

  # Order service
  order/internal/service:
    config:
      all: true

  # Order repository
  order/internal/repository:
    config:
      all: true

  # Payment service
  payment/internal/service:
    config:
      all: true