// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function with given fields: ctx, uuid
func (_m *OrderRepository) GetOrder(ctx context.Context, uuid string) (*model.Order, bool) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, bool)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// OrderRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderRepository_Expecter) GetOrder(ctx interface{}, uuid interface{}) *OrderRepository_GetOrder_Call {
	return &OrderRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, uuid)}
}

func (_c *OrderRepository_GetOrder_Call) Run(run func(ctx context.Context, uuid string)) *OrderRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrder_Call) Return(_a0 *model.Order, _a1 bool) *OrderRepository_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*model.Order, bool)) *OrderRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PutOrder provides a mock function with given fields: ctx, uuid, order
func (_m *OrderRepository) PutOrder(ctx context.Context, uuid string, order *model.Order) {
	_m.Called(ctx, uuid, order)
}

// OrderRepository_PutOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutOrder'
type OrderRepository_PutOrder_Call struct {
	*mock.Call
}

// PutOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - order *model.Order
func (_e *OrderRepository_Expecter) PutOrder(ctx interface{}, uuid interface{}, order interface{}) *OrderRepository_PutOrder_Call {
	return &OrderRepository_PutOrder_Call{Call: _e.mock.On("PutOrder", ctx, uuid, order)}
}

func (_c *OrderRepository_PutOrder_Call) Run(run func(ctx context.Context, uuid string, order *model.Order)) *OrderRepository_PutOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.Order))
	})
	return _c
}

func (_c *OrderRepository_PutOrder_Call) Return() *OrderRepository_PutOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderRepository_PutOrder_Call) RunAndReturn(run func(context.Context, string, *model.Order)) *OrderRepository_PutOrder_Call {
	_c.Run(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
